
# 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 
# 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 
# 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 
# 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력



SELECT A.CAR_ID, A.CAR_TYPE, 
       FLOOR(A.DAILY_FEE * 30 * (1 - C.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
  ON A.CAR_TYPE = C.CAR_TYPE
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
  ON A.CAR_ID = B.CAR_ID
 AND B.START_DATE <= '2022-11-30'
 AND B.END_DATE >= '2022-11-01'
WHERE A.CAR_TYPE IN ('세단', 'SUV')
  AND C.DURATION_TYPE = '30일 이상'
  AND B.CAR_ID IS NULL  -- 11월에 대여 이력 없는 것만
  AND A.DAILY_FEE * 30 * (1 - C.DISCOUNT_RATE / 100) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;


