-- 코드를 입력하세요
# SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF WHERE TOTAL_ORDER > 3000
# SELECT FLAVOR, INGREDITENT_TYPE FROM ICECREAM_INFO WHERE INGREDITENT_TYPE = "fruit_based"
SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN ICECREAM_INFO II
ON FH.FLAVOR = II.FLAVOR
WHERE FH.TOTAL_ORDER > 3000
  AND II.INGREDIENT_TYPE = 'fruit_based'
ORDER BY FH.TOTAL_ORDER DESC;


