-- 코드를 입력하세요
SELECT a.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b
ON a.CAR_ID = b.CAR_ID
WHERE MONTH(b.START_DATE) = 10
AND a.CAR_TYPE = '세단'
GROUP BY a.CAR_ID
ORDER BY a.CAR_ID DESC