-- 코드를 입력하세요
SELECT UGB.TITLE, UGB.BOARD_ID, UBR.REPLY_ID, UBR.WRITER_ID, UBR.CONTENTS, DATE_FORMAT(UBR.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_REPLY UBR
ON UGB.BOARD_ID = UBR.BOARD_ID
WHERE UGB.CREATED_DATE LIKE '2022-10%'
ORDER BY UBR.CREATED_DATE ASC, UGB.TITLE ASC;